---
# tasks file for linux.add_user
- name: Create users from list.
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
  with_items: "{{ users_vars }}"

- name: Copy shell_config when it exists.
  copy:
    src: "{{ item.shell_config }}"
    dest: "/home/{{ item.name }}/{{ item.shell_config }}"
    mode: 0600
    owner: "{{ item.name }}"
  with_items: "{{ users_vars }}"

- name: Edit admin group in sudoers.
  lineinfile:
    dest: /etc/sudoers
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'

- name: If ZSH, install oh my zsh.
  shell: sudo -u {{ item.user }} sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
  with_items: "{{ users_vars }}"
  when: item.shell == '/bin/zsh'
