---
# tasks file for linux.packages
- name: Install apt packages (if defined).
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ apt_packages | default([])  }}"
  when: apt_packages is defined

- name: Install pip packages (if defined).
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ pip_packages | default([])  }}"
  when: pip_packages is defined

- name: Install npm packages (if defined).
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items: "{{ npm_packages | default([]) }}"
  when: npm_packages is defined
